[package]
name = "bf-frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
sycamore = "0.9.2"
wasm-bindgen = "0.2.89"
bf = { path = ".." }
web-sys = { version = "0.3", features = ["HtmlTextAreaElement", "Element"] }