[package]
name = "bf"
version = "0.1.0"
edition = "2021"
description = "Brainfuck to C transpiler â€” CLI and WebAssembly"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "bf"
path = "src/main.rs"

[dependencies]
wasm-bindgen = "0.2.89"

[profile.release]
opt-level = 3
lto = true
